//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCReportViwer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateArea
    {
        public int StateID { get; set; }
        public string Statename { get; set; }
        public decimal Area { get; set; }
    }
}
